version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: user_management_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  ipfs:
    image: ipfs/kubo
    container_name: ipfs_node
    restart: always
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  pgdata:
  ipfs_staging:
  ipfs_data:
